name: SonarQube

on:
  push:
    branches:
      - develop

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.302'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Install SonarQube Cloud scanner
        shell: powershell
        run: |
          dotnet tool update dotnet-sonarscanner --global

      - name: Build and analyze
        shell: powershell
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          Set-Location "$env:GITHUB_WORKSPACE\Backend"

          Write-Host "===== CURRENT DIRECTORY ====="
          Get-Location

          Write-Host "===== SOLUTION FILE ====="
          Get-ChildItem TaskManagementSystem.sln

          Write-Host "===== SONAR BEGIN ====="
          dotnet sonarscanner begin /k:"Saminakalwar_cohort-9-dotnet-14745-samina" /o:"myrepo-analysis" /d:sonar.token="$env:SONAR_TOKEN"

          Write-Host "===== RESTORE ====="
          dotnet restore TaskManagementSystem.sln

          Write-Host "===== BUILD ====="
          dotnet build TaskManagementSystem.sln --no-restore --configuration Release

          Write-Host "===== SONAR END ====="
          dotnet sonarscanner end /d:sonar.token="$env:SONAR_TOKEN"